### PR TITLE
createEventFromKeystroke: use get-window and get-document

### PR DESCRIPTION
**Pull request by mightyiam**

### CODE REVIEW

**Comment by mightyiam** [comment]
How are you? Following up from #17, get-window [does not assume](https://github.com/webmodules/get-window/commit/e6e18e39691adc5146fea410471d270ddf0311ba) browser environment any more.

**Comment by mightyiam** [comment]
So this can be another small step towards #7.

**Comment by mightyiam** [comment]
@eventualbuddha can you please take a look?

**Comment by eventualbuddha** [comment]
Sorry for the delay in getting to this. I'll take a look.

**Comment by eventualbuddha** [comment]
This needs to be done in such a way that there is a `dist/keysim.browser.js` file bundles its dependencies. This will probably involve some hacks to turn get-document and get-window into ES6. I would probably do this using Esperanto's [`transform`](https://github.com/esperantojs/esperanto/wiki/Bundling-multiple-ES6-modules#transform) option.

**Pull request closed without merging**
